### ISSUE TITLE
Delay and out of view in landscape

### ISSUE THREAD

**Issue by kaushalkumar86** [martin-stone/hsv-alpha-color-picker-android#39] opened 2017-12-06 10:50 UTC
First of all, thanks for the project.
I am using your project library in my app. There is a delay in opening the picker view after tapping ( I am using your **colorpicker in alertdialog**). In Alertdialog, I have managed to change its layout from portrait to landscape without destroying the activity (via dialog dismiss and re create), but the view in landscape (whether its created for the 1st time or recreated) goes out of view at bottom.
Only the view of main color arc selector goes out a few dps, rest alpha selector and sat selector are fine.
I can send you a snapshot if it helps you.

**Comment by kaushalkumar86** [comment] 2017-12-06 11:06
I tested it more, the issue happens when I use the Alertdialog with Title.
Otherwise its ok when used without title.

**Comment by martin-stone** [comment] 2017-12-06 13:29
Glad you found a workaround for the landscape layout. Assuming you're OK without a title, I'm going to close this as a duplicate of #38.

**Closed as completed by martin-stone** 2017-12-06 13:29 UTC
Labels: duplicate

**Comment by kaushalkumar86** [comment] 2017-12-06 13:35
Thanks for replying,

For now I am ok without title, but please lemme know if you fix it in
upcoming updates.

KKA
+918083562177

**Comment by kaushalkumar86** [comment] 2018-01-26 07:29
Thanks, delay is solved in this new update.
